name: my_json_view
version: 1.0.0
description: A customizable Flutter widget for displaying JSON data in a tree view with search and expand/collapse functionality.
homepage: https://github.com/karnadii/my_json_view
repository: https://github.com/karnadii/my_json_view
issue_tracker: https://github.com/karnadii/my_json_view/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Or your preferred linter

# The "flutter" section is usually not needed for a simple widget package.